title: "Trigo Limpo"
author: "dx"
description: ""
lang: "pt"

# Page settings
permalink: /:title/          # see https://jekyllrb.com/docs/permalinks/
date_format: "%d %B %Y"      # see http://shopify.github.io/liquid/filters/date/
hide_title: false            # remove site heading in the header
post_footer: true            # show previous and next links at the end of each post

# Theme settings
dark_theme: false            # use the dark mode as default
dark_header: true            # keep the header dark
# style: minimal             # use a simpler style inspired by the minima theme

navigation:                  # (optional) site navigation in the header
  - index.html
  - about.md
  - archive.md
#  - README.md
#  - title: "https://"       # linking external sites is also supported

icons:                       # (optional) icons in the header, see http://fontawesome.com/icons
  envelope: "mailto:trigolimpo@mailbox.org"
#  github: "https://github.com/niklasbuschmann/contrast"
  rss: "/feed.xml"

# Pagination
show_excerpts: true          # preview articles on the home page
paginate: 3                  # number of articles per page
excerpt_separator: "\n\n\n"  # indicate the end of the excerpt by two blank lines

comments:                    # embed disqus or isso comments
#  disqus: ""
#  isso: ""

plugins: 
 - jekyll-feed
 - jekyll-paginate
 - jekyll-default-layout

# mathjax: true
